### ISSUE TITLE
templates still points to signalcraft

### ISSUE THREAD

**Issue by boelle** [rmalbrecht/VaillantCloud#10]
![Image](https://github.com/user-attachments/assets/6b61a889-e376-488c-9b00-378e7854d430)

![Image](https://github.com/user-attachments/assets/2d29afc3-df15-4d55-90bc-51336346861d)

**Comment by rmalbrecht** [comment]
fixed

**Comment by boelle** [comment]
when i try an open an issue the teplates are still the same with links to signalcraft
